# Generated by Django 5.2 on 2025-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_exchangeproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидает'), ('A', 'Принята')], default='W', max_length=1),
        ),
    ]
