# Generated by Django 5.2 on 2025-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_exchangeproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидает'), ('A', 'Принята'), ('R', 'Отклонена')], default='W', max_length=1),
        ),
    ]
